### ISSUE TITLE
A migration Problem? 

### ISSUE THREAD

**Issue by DrThuraya** [RegardsOss/regards-frontend#1]
Hi all,

I am trying to test the frontend package locally after some modifications,

When typing `npm run start:withpreprod` I got the error message below: 

![img1](https://user-images.githubusercontent.com/21196992/147574696-04ec2759-ab81-45ab-9659-4652b4be87ea.png)

to fix the problem, I ran `npm ls webpack-cli`which which returns --> ERR! invalid: webpack-cli@4.6.0 and `npm ls webpack-dev-server` that returns --> webpack-dev-server@3.11.3`. 

I updated the webpack-cli to the latest stable version and ran `npm run start:withpreprod`. I got another error message. Apparently node version is not supported by the regular expression `/(\p{Uppercase_Letter}+|\p{Lowercase_Letter}|\d)(\p{Uppercase_Letter}+)/gu,`

![screen1](https://user-images.githubusercontent.com/21196992/147574739-0bf9b60f-6468-4ba2-bb29-da86fd39b5ef.png)

I upgraded the node version to **10.20** and I got this error message: 

![screen2](https://user-images.githubusercontent.com/21196992/147575775-c6a96459-12c7-45cc-8085-561db4fb2488.png)

Any help please?

**Comment by sebastienbinda** [comment]
Hello, our documentation is not up to date concerning the minimum vesion of node required.
The minimum version required are :
 - node : 12.13.0+
 - npm : 5.7.1+
 
 Can you try after updating those tools ?

**Comment by DrThuraya** [comment]
Hi, 

I tried with : 

- node: v17.3.0
- npm: 8.3.0

and I got this error: 

![Screen Shot 2022-01-05 at 5 56 47 PM](https://user-images.githubusercontent.com/21196992/148258428-7f253e62-bbb0-4459-be9c-284238389c97.png)

**Comment by sebastienbinda** [comment]
Hi, 
Indeed since version 16+ of node (with v8+ npm) we have to update the webpack-cli dependency. To do so, you can update the package.json file at webapp root directory and bump webpack-cli version du 4.9.0.
Once  this done, you can run "npm install" to update dependencies and then run your local server with "start:with...".
Remember to update the webconf if you use the start:withpreprod cause this action is by default configurer to run regards frontend with a predifenied regards backend server IP (for dev purpose  on cs group environment).

Sébastien.

**Comment by DrThuraya** [comment]
Thank you ! it works perfectly.

**Comment by sebastienbinda** [comment]
Correction will be done in next version release v1.8.0.
